title: Steven Leabo
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio site for Frontend Web Developer Steven Leabo who lives in Central New York (Syracuse) and likes to build cool stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
  - jekyll-feed
